### ISSUE TITLE
A request

### ISSUE THREAD

**Issue by sleepycatcoding** [salah-rashad/pz_dead_zone#1]
Hi!

Could you please remove the asset repo you forked? and then delete this issue, thanks.

**Comment by salah-rashad** [comment]
Done

**Comment by sleepycatcoding** [comment]
Just to make sure, you deleted it, not just privated it, I don't want my GitHub user to stay as the author of the commits.

**Comment by sleepycatcoding** [comment]
Also did you download the server package from the Ruffle issue report, if so I would like you to delete that, I don't want it out there anymore.

**Comment by salah-rashad** [comment]
What happened bro? Like you are being threatened or something?!

Also, yes I made it private but I will never use it anywhere, just keeping them for memories.

And I don't know anything about the server package.

**Comment by sleepycatcoding** [comment]
Could you delete it and fork this instead? https://github.com/glennhenry/tlsdz-assets

**Comment by sleepycatcoding** [comment]
> What happened bro? Like you are being threatened or something?!

I am not being threatened, I just don't want this stuff to exist anymore sorry.

**Comment by sleepycatcoding** [comment]
> And I don't know anything about the server package. 

Well you commented on ruffle issue 13992, (I don't want to link it here)

**Comment by salah-rashad** [comment]
Done 
![IMG](https://github.com/salah-rashad/pz_dead_zone/assets/35843293/588a1b24-734a-401a-afe1-1ab174bb08f1)

**Comment by sleepycatcoding** [comment]
Thanks, and you have no local copies, correct? And no server code I had hosted previously, I don't want it out there.

**Comment by salah-rashad** [comment]
No local copies, no forks and no server code.

**Comment by sleepycatcoding** [comment]
Could you now delete this issue, please? Cannot do that myself.
